/*  zynqmp-pssysmon-temp.c - The simplest kernel module.

* Copyright (C) 2013-2022 Xilinx, Inc
* Copyright (c) 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
*
*   This program is free software; you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation; either version 2 of the License, or
*   (at your option) any later version.

*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License along
*   with this program. If not, see <http://www.gnu.org/licenses/>.

*/
#include <linux/kernel.h>
#include <linux/init.h>
#include <linux/module.h>
#include <linux/slab.h>
#include <linux/io.h>
#include <linux/interrupt.h>
#include <linux/device.h>
#include <linux/clk.h>

#include <linux/of_address.h>
#include <linux/of_device.h>
#include <linux/of_platform.h>
#include <linux/thermal.h>
#include <linux/err.h>

/* Standard module information, edit as appropriate */
MODULE_LICENSE("GPL");
MODULE_AUTHOR
    ("Xilinx Inc.");
MODULE_DESCRIPTION
    ("zynqmp-pssysmon-temp - loadable module template generated by petalinux-create -t modules");

#define DRIVER_NAME "zynqmp-pssysmon-temp"



/* Simple example of how to receive command line parameters to your module.
   Delete if you don't need them */
unsigned myint = 0xdeadbeef;
char *mystr = "default";

module_param(myint, int, S_IRUGO);
module_param(mystr, charp, S_IRUGO);

struct zynqmp_pssysmon_temp_local {
	int irq;
	unsigned long mem_start;
	unsigned long mem_end;
	void __iomem *base_addr;
};

/* Thermal sensor dev structure */
struct thermal_sensor_device {
	void __iomem *base;
};

static int zynqmp_pssysmon_temp_get_temp(struct thermal_zone_device *tzd, int *temp)
{
	struct thermal_sensor_device *tsd = tzd->devdata;
	int val;
	val = ioread32(tsd->base);
	/* Convert the register value to temperature in C using Temperature Transfer Functions described in UG580 */
	/* The adc values are available in 15:6 */
	//val = (val >> 6) & 0x3FF;
	val = val & 0xFFFF;
	/* Convert to temperature using equation Temperature (C) = ((ADC x 509.3140064)/2^bits) - 280.23087870 */
	//val = (int)((double)val * (double)0.49737696 - (double)280.23087870);
	val = (val >> 7) - 280;
	/* Check overflow and set value at addr temp */
	*temp = val * 1000;
	return 0;
}

static int zynqmp_pssysmon_temp_set_emul_temp(struct thermal_zone_device *tzd, int temp)
{
	struct thermal_sensor_device *tsd = tzd->devdata;
	iowrite32(temp, tsd->base);
	return 0;
}

static struct thermal_zone_device_ops ops = {
	.get_temp = zynqmp_pssysmon_temp_get_temp,
	// .set_trips = zynqmp_pssysmon_temp_set_trips,
	// .get_trip_type = zynqmp_pssysmon_temp_get_trip_type,
	// .get_trip_temp = zynqmp_pssysmon_temp_get_trip_temp,
	// .bind = zynqmp_pssysmon_temp_bind,
	// .unbind = zynqmp_pssysmon_temp_unbind,
	.set_emul_temp = zynqmp_pssysmon_temp_set_emul_temp,
};

static irqreturn_t zynqmp_pssysmon_temp_irq(int irq, void *lp)
{
	printk("zynqmp-pssysmon-temp interrupt\n");
	return IRQ_HANDLED;
}

static int zynqmp_pssysmon_temp_probe(struct platform_device *pdev)
{
	struct resource *r_irq; /* Interrupt resources */
	struct resource *r_mem; /* IO mem resources */
	struct device *dev = &pdev->dev;
	struct zynqmp_pssysmon_temp_local *lp = NULL;

	struct thermal_zone_device *zynqmp_thermal = NULL;
	struct thermal_sensor_device *stdev;
	struct device_node *np = NULL;

	int rc = 0;
	dev_info(dev, "Device Tree Probing\n");
	/* Get iospace for the device */
	r_mem = platform_get_resource(pdev, IORESOURCE_MEM, 0);
	if (!r_mem) {
		dev_err(dev, "invalid address\n");
		return -ENODEV;
	}
	lp = (struct zynqmp_pssysmon_temp_local *) kmalloc(sizeof(struct zynqmp_pssysmon_temp_local), GFP_KERNEL);
	if (!lp) {
		dev_err(dev, "Cound not allocate zynqmp-pssysmon-temp device\n");
		return -ENOMEM;
	}
	dev_set_drvdata(dev, lp);
	lp->mem_start = r_mem->start;
	lp->mem_end = r_mem->end;

	if (!request_mem_region(lp->mem_start,
				lp->mem_end - lp->mem_start + 1,
				DRIVER_NAME)) {
		dev_err(dev, "Couldn't lock memory region at %p\n",
			(void *)lp->mem_start);
		rc = -EBUSY;
		goto error1;
	}

	lp->base_addr = ioremap(lp->mem_start, lp->mem_end - lp->mem_start + 1);
	if (!lp->base_addr) {
		dev_err(dev, "zynqmp-pssysmon-temp: Could not allocate iomem\n");
		rc = -EIO;
		goto error2;
	}

	stdev = devm_kzalloc(&pdev->dev, sizeof(*stdev), GFP_KERNEL);
	if (!stdev)
		return -ENOMEM;

	np = devm_kzalloc(&pdev->dev, sizeof(*np), GFP_KERNEL);
	if (!np)
		return -ENOMEM;
	
	/*  */
	*np = *dev->of_node;
	
	stdev->base = lp->base_addr;
	// zynqmp_thermal = thermal_zone_device_register("pssysmon-temp", 0, 0,
	// 			stdev, &ops, NULL, 0, 0);
	// if (IS_ERR(zynqmp_thermal)) {
	// 	dev_err(&pdev->dev, "thermal zone device is NULL\n");
	// 	rc = PTR_ERR(zynqmp_thermal);
	// }

	/* Get the id of the sensor from the device tree */
	int id;		
	rc = of_property_read_u32(dev->of_node, "id", &id);
    if (rc < 0) {
        dev_err(dev, "Unable to read 'id' property\n");
        return rc;
    }

	/* print ID */
	dev_info(dev, "ID: %d\n", id);

	/* Register sensor in device tree thermal zones refering to it using thermal_zone_of_sensor_register() */
	zynqmp_thermal = thermal_of_zone_register(dev->of_node, id, stdev, &ops);
	if (IS_ERR(zynqmp_thermal)) {
		dev_err(dev, "(thermal_zone_of_sensor_register) thermal zone device is NULL\n");
		rc = PTR_ERR(zynqmp_thermal);
	}


	/* Get IRQ for the device */
	r_irq = platform_get_resource(pdev, IORESOURCE_IRQ, 0);
	if (!r_irq) {
		dev_info(dev, "no IRQ found\n");
		dev_info(dev, "zynqmp-pssysmon-temp at 0x%08x mapped to 0x%08x\n",
			(unsigned int __force)lp->mem_start,
			(unsigned int __force)lp->base_addr);
		return 0;
	}
	lp->irq = r_irq->start;
	rc = request_irq(lp->irq, &zynqmp_pssysmon_temp_irq, 0, DRIVER_NAME, lp);
	if (rc) {
		dev_err(dev, "testmodule: Could not allocate interrupt %d.\n",
			lp->irq);
		goto error3;
	}

	

	dev_info(dev,"zynqmp-pssysmon-temp at 0x%08x mapped to 0x%08x, irq=%d\n",
		(unsigned int __force)lp->mem_start,
		(unsigned int __force)lp->base_addr,
		lp->irq);
	return 0;
error3:
	free_irq(lp->irq, lp);
error2:
	release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
error1:
	kfree(lp);
	dev_set_drvdata(dev, NULL);
	return rc;
}

static int zynqmp_pssysmon_temp_remove(struct platform_device *pdev)
{
	struct device *dev = &pdev->dev;
	struct zynqmp_pssysmon_temp_local *lp = dev_get_drvdata(dev);
	free_irq(lp->irq, lp);
	iounmap(lp->base_addr);
	release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
	kfree(lp);
	dev_set_drvdata(dev, NULL);
	return 0;
}

#ifdef CONFIG_OF
static struct of_device_id zynqmp_pssysmon_temp_of_match[] = {
	{ .compatible = "xlnx,zynqmp-pssysmon-temp", },
	{ /* end of list */ },
};
MODULE_DEVICE_TABLE(of, zynqmp_pssysmon_temp_of_match);
#else
# define zynqmp_pssysmon_temp_of_match
#endif


static struct platform_driver zynqmp_pssysmon_temp_driver = {
	.driver = {
		.name = DRIVER_NAME,
		.owner = THIS_MODULE,
		.of_match_table	= zynqmp_pssysmon_temp_of_match,
	},
	.probe		= zynqmp_pssysmon_temp_probe,
	.remove		= zynqmp_pssysmon_temp_remove,
};

static int __init zynqmp_pssysmon_temp_init(void)
{
	printk("<1>Hello module world.\n");
	printk("<1>Module parameters were (0x%08x) and \"%s\"\n", myint,
	       mystr);

	return platform_driver_register(&zynqmp_pssysmon_temp_driver);
}


static void __exit zynqmp_pssysmon_temp_exit(void)
{
	platform_driver_unregister(&zynqmp_pssysmon_temp_driver);
	printk(KERN_ALERT "Goodbye module world.\n");
}

module_init(zynqmp_pssysmon_temp_init);
module_exit(zynqmp_pssysmon_temp_exit);
