/*  soft-pwm-fan.c - hrtimer soft-PWM GPIO fan cooling device.
 *
 * Copyright (c) 2024 Oren Collaco.
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 * Evolution of simple-gpio-fan: instead of a two-state (on/off) cooling
 * device, this exposes a multi-state cooling device and drives the fan GPIO
 * with a software PWM generated by an hrtimer. Each cooling state maps to a
 * duty cycle; the Linux thermal framework picks the state from the
 * device-tree trip points, giving proportional (ramping) fan speed with no
 * FPGA changes.
 *
 * The GPIO is driven by *logical* level (gpiod_set_value(gpio, 1) == fan on).
 * Express the board's active-low wiring with GPIO_ACTIVE_LOW in the device
 * tree so the driver logic stays clean.
 */
#include <linux/kernel.h>
#include <linux/init.h>
#include <linux/module.h>
#include <linux/slab.h>
#include <linux/hrtimer.h>
#include <linux/ktime.h>
#include <linux/of.h>
#include <linux/of_device.h>
#include <linux/of_platform.h>
#include <linux/platform_device.h>
#include <linux/thermal.h>
#include <linux/err.h>
#include <linux/gpio/consumer.h>

MODULE_LICENSE("GPL");
MODULE_AUTHOR("Oren Collaco");
MODULE_DESCRIPTION("soft-pwm-fan - hrtimer soft-PWM GPIO fan cooling device");

#define DRIVER_NAME		"soft-pwm-fan"

#define DEFAULT_NUM_LEVELS	10	/* cooling states 1..N (0 = off)      */
#define DEFAULT_MIN_DUTY	30	/* lowest duty (%) that keeps spinning */
#define DEFAULT_FREQ_HZ		100	/* soft-PWM carrier frequency          */

#define MIN_FREQ_HZ		1
#define MAX_FREQ_HZ		2000	/* keep hrtimer wakeups reasonable     */

struct soft_pwm_fan {
	struct gpio_desc *gpio;
	struct thermal_cooling_device *cdev;
	struct hrtimer timer;

	u32 num_levels;			/* == max cooling state               */
	u32 min_duty;			/* percent                            */
	u32 freq_hz;
	u64 period_ns;

	/* Updated by set_cur_state (process ctx), read by timer (irq ctx). */
	u64 on_ns;			/* high time within a period          */
	u64 off_ns;			/* low time within a period           */

	unsigned long cur_state;
	bool running;			/* timer active (0 < duty < 100)      */
	bool level_high;		/* current phase of the PWM waveform  */
};

/*
 * hrtimer callback: toggle the GPIO and re-arm for the next phase.
 * Runs in hard-irq context; gpiod_set_value() on the Xilinx AXI GPIO is an
 * MMIO write and is safe here.
 */
static enum hrtimer_restart soft_pwm_fan_tick(struct hrtimer *t)
{
	struct soft_pwm_fan *fan = container_of(t, struct soft_pwm_fan, timer);

	if (fan->level_high) {
		gpiod_set_value(fan->gpio, 0);		/* end of ON phase */
		fan->level_high = false;
		hrtimer_forward_now(t, ns_to_ktime(READ_ONCE(fan->off_ns)));
	} else {
		gpiod_set_value(fan->gpio, 1);		/* start of ON phase */
		fan->level_high = true;
		hrtimer_forward_now(t, ns_to_ktime(READ_ONCE(fan->on_ns)));
	}
	return HRTIMER_RESTART;
}

/* Stop the PWM waveform and force a steady level (0 = off, 1 = full on). */
static void soft_pwm_fan_set_steady(struct soft_pwm_fan *fan, int value)
{
	if (fan->running) {
		hrtimer_cancel(&fan->timer);
		fan->running = false;
	}
	gpiod_set_value(fan->gpio, value);
	fan->level_high = value ? true : false;
}

static int soft_pwm_fan_set_cur_state(struct thermal_cooling_device *cdev,
				      unsigned long state)
{
	struct soft_pwm_fan *fan = cdev->devdata;
	u32 duty;

	if (state > fan->num_levels)
		state = fan->num_levels;

	fan->cur_state = state;

	if (state == 0) {			/* fully off */
		soft_pwm_fan_set_steady(fan, 0);
		return 0;
	}

	/* state 1..N -> duty min_duty..100 (linear) */
	duty = fan->min_duty +
	       (100 - fan->min_duty) * state / fan->num_levels;
	if (duty >= 100) {			/* fully on */
		soft_pwm_fan_set_steady(fan, 1);
		return 0;
	}

	WRITE_ONCE(fan->on_ns, div_u64(fan->period_ns * duty, 100));
	WRITE_ONCE(fan->off_ns, fan->period_ns - READ_ONCE(fan->on_ns));

	if (!fan->running) {
		fan->running = true;
		fan->level_high = true;
		gpiod_set_value(fan->gpio, 1);
		hrtimer_start(&fan->timer, ns_to_ktime(READ_ONCE(fan->on_ns)),
			      HRTIMER_MODE_REL);
	}
	/* If already running, the new on/off times take effect next cycle. */
	return 0;
}

static int soft_pwm_fan_get_cur_state(struct thermal_cooling_device *cdev,
				      unsigned long *state)
{
	struct soft_pwm_fan *fan = cdev->devdata;

	*state = fan->cur_state;
	return 0;
}

static int soft_pwm_fan_get_max_state(struct thermal_cooling_device *cdev,
				      unsigned long *state)
{
	struct soft_pwm_fan *fan = cdev->devdata;

	*state = fan->num_levels;
	return 0;
}

static const struct thermal_cooling_device_ops soft_pwm_fan_ops = {
	.get_max_state = soft_pwm_fan_get_max_state,
	.get_cur_state = soft_pwm_fan_get_cur_state,
	.set_cur_state = soft_pwm_fan_set_cur_state,
};

static int soft_pwm_fan_probe(struct platform_device *pdev)
{
	struct device *dev = &pdev->dev;
	struct device_node *np = dev->of_node;
	struct soft_pwm_fan *fan;
	int rc;

	fan = devm_kzalloc(dev, sizeof(*fan), GFP_KERNEL);
	if (!fan)
		return -ENOMEM;

	/* Request the fan line, initially deasserted (fan off). */
	fan->gpio = devm_gpiod_get_index(dev, NULL, 0, GPIOD_OUT_LOW);
	if (IS_ERR(fan->gpio)) {
		rc = PTR_ERR(fan->gpio);
		dev_err(dev, "failed to get fan gpio: %d\n", rc);
		return rc;
	}

	/* Tunables (all optional, with sane defaults). */
	if (of_property_read_u32(np, "num-levels", &fan->num_levels) ||
	    fan->num_levels == 0)
		fan->num_levels = DEFAULT_NUM_LEVELS;

	if (of_property_read_u32(np, "min-duty-percent", &fan->min_duty) ||
	    fan->min_duty > 100)
		fan->min_duty = DEFAULT_MIN_DUTY;

	if (of_property_read_u32(np, "pwm-frequency-hz", &fan->freq_hz))
		fan->freq_hz = DEFAULT_FREQ_HZ;
	fan->freq_hz = clamp_t(u32, fan->freq_hz, MIN_FREQ_HZ, MAX_FREQ_HZ);

	fan->period_ns = div_u64(NSEC_PER_SEC, fan->freq_hz);

	hrtimer_init(&fan->timer, CLOCK_MONOTONIC, HRTIMER_MODE_REL);
	fan->timer.function = soft_pwm_fan_tick;
	fan->cur_state = 0;
	fan->running = false;

	fan->cdev = devm_thermal_of_cooling_device_register(dev, np,
			(char *)pdev->name, fan, &soft_pwm_fan_ops);
	if (IS_ERR(fan->cdev)) {
		rc = PTR_ERR(fan->cdev);
		dev_err(dev, "failed to register cooling device: %d\n", rc);
		return rc;
	}

	platform_set_drvdata(pdev, fan);
	dev_info(dev,
		 "soft-pwm-fan: %u levels, min %u%%, %u Hz (period %llu ns)\n",
		 fan->num_levels, fan->min_duty, fan->freq_hz, fan->period_ns);
	return 0;
}

static int soft_pwm_fan_remove(struct platform_device *pdev)
{
	struct soft_pwm_fan *fan = platform_get_drvdata(pdev);

	if (fan)
		soft_pwm_fan_set_steady(fan, 0);	/* fan off, timer stopped */
	return 0;
}

static const struct of_device_id soft_pwm_fan_of_match[] = {
	{ .compatible = "xlnx,soft-pwm-fan", },
	{ /* end of list */ },
};
MODULE_DEVICE_TABLE(of, soft_pwm_fan_of_match);

static struct platform_driver soft_pwm_fan_driver = {
	.driver = {
		.name		= DRIVER_NAME,
		.owner		= THIS_MODULE,
		.of_match_table	= soft_pwm_fan_of_match,
	},
	.probe	= soft_pwm_fan_probe,
	.remove	= soft_pwm_fan_remove,
};

module_platform_driver(soft_pwm_fan_driver);
