/*  simple-gpio-fan.c - The simplest kernel module.

* Copyright (C) 2013-2022 Xilinx, Inc
* Copyright (c) 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
*
*   This program is free software; you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation; either version 2 of the License, or
*   (at your option) any later version.

*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License along
*   with this program. If not, see <http://www.gnu.org/licenses/>.

*/
#include <linux/kernel.h>
#include <linux/init.h>
#include <linux/module.h>
#include <linux/slab.h>
#include <linux/io.h>
#include <linux/interrupt.h>
#include <linux/device.h>
#include <linux/clk.h>

#include <linux/of_address.h>
#include <linux/of_device.h>
#include <linux/of_platform.h>
#include <linux/thermal.h>
#include <linux/err.h>
#include <linux/gpio/consumer.h>

/* Standard module information, edit as appropriate */
MODULE_LICENSE("GPL");
MODULE_AUTHOR
    ("Xilinx Inc.");
MODULE_DESCRIPTION
    ("simple-gpio-fan - loadable module template generated by petalinux-create -t modules");

#define DRIVER_NAME "simple-gpio-fan"
#define GPIOD_OUT 0

/* Simple example of how to receive command line parameters to your module.
   Delete if you don't need them */
unsigned myint = 0xdeadbeef;
char *mystr = "default";

// module_param(myint, int, S_IRUGO);
// module_param(mystr, charp, S_IRUGO);

struct gpio_speed_val_map {
	unsigned int speed;
	unsigned int gpio_val;
};

struct simple_gpio_fan_local {
	int num_gpios;
	struct gpio_desc **gpios;
	int num_speeds;
	struct gpio_speed_val_map *speed_map;
	struct thermal_cooling_device *cdev;
};

static void simple_gpio_fan_turn_on(struct simple_gpio_fan_local *lp)
{
	printk("simple-gpio-fan probe on\n");
	/* set output to 0 */
	gpiod_set_value(lp->gpios[0], 0);
}

static void simple_gpio_fan_turn_off(struct simple_gpio_fan_local *lp)
{
	printk("simple-gpio-fan probe off\n");
	/* set output to 1 */
	gpiod_set_value(lp->gpios[0], 1);
}

static int simple_gpio_fan_set_current_state(struct thermal_cooling_device *cdev, unsigned long state)
{
	struct simple_gpio_fan_local *fan_data = cdev->devdata;
	// int ret = 0;
	// ret = gpiod_get_direction(fan_data->gpios[0]);
	// if (ret < 0) {
	// 	pr_err("Error getting direction of fan gpio 0\n");
	// 	return ret;
	// }
	// if (ret != GPIOD_OUT) {
	// 	pr_err("Fan gpio 0 is not an output\n");
	// 	/* Try setting as output */
	// 	ret = gpiod_direction_output(fan_data->gpios[0], 0);
	// 	if (ret) {
	// 		pr_err("Error setting direction of fan gpio to out\n");
	// 		return -EINVAL;
	// 	}
	// }
	/* Verify state and fix */
	unsigned int value = 0;
	if (state >= 1) {
		value = 0;
	}
	if (state <= 0) {
		value = 1;
	}

	/* Set output to state */
	gpiod_set_value(fan_data->gpios[0], value);
	/* Print set state */
	printk("simple-gpio-fan set current state: %lu\n", value);
	return 0;
}

static int simple_gpio_fan_get_current_state(struct thermal_cooling_device *cdev, unsigned long *state)
{
	struct simple_gpio_fan_local *fan_data = cdev->devdata;
	/* Valid that the gpio is correct by checking direction */
	int ret = 0;
	// ret = gpiod_get_direction(fan_data->gpios[0]);
	// if (ret < 0) {
	// 	pr_err("Error getting direction of fan gpio 0\n");
	// 	return ret;
	// }
	// if (ret != GPIOD_OUT) {
	// 	pr_err("Fan gpio 0 is not an output\n");
	// 	/* Try setting as output */
	// 	ret = gpiod_direction_output(fan_data->gpios[0], 0);
	// 	if (ret) {
	// 		pr_err( "Error setting direction of fan gpio to out\n");
	// 		return -EINVAL;
	// 	}
	// }

	/* Get the value of the gpio */
	ret = gpiod_get_value(fan_data->gpios[0]);

	unsigned int value = 0;
	if (ret >= 1) {
		value = 0;
	}
	if (ret <= 0) {
		value = 1;
	}

	/* set state to current state */
	*state = value;
	/* Print read state */
	printk("simple-gpio-fan get current state: %d\n", value);
	
	return 0;
}

static int simple_gpio_fan_get_max_state(struct thermal_cooling_device *cdev, unsigned long *state)
{
	*state = 1;
	return 0;
}

static const struct thermal_cooling_device_ops gpio_fan_cool_ops = {
	.get_max_state = simple_gpio_fan_get_max_state,
	.get_cur_state = simple_gpio_fan_get_current_state,
	.set_cur_state = simple_gpio_fan_set_current_state,
};

static irqreturn_t simple_gpio_fan_irq(int irq, void *lp)
{
	printk("simple-gpio-fan interrupt\n");
	return IRQ_HANDLED;
}

static int simple_gpio_fan_probe(struct platform_device *pdev)
{
	struct resource *r_irq; /* Interrupt resources */
	struct resource *r_mem; /* IO mem resources */
	struct device *dev = &pdev->dev;
	struct device_node *np = dev->of_node;
	struct simple_gpio_fan_local *lp = NULL;

	int rc = 0;
	dev_info(dev, "Device Tree Probing\n");
	/* Get iospace for the device */
	// r_mem = platform_get_resource(pdev, IORESOURCE_MEM, 0);
	// if (!r_mem) {
	// 	dev_err(dev, "invalid address\n");
	// 	return -ENODEV;
	// }
	lp = (struct simple_gpio_fan_local *) kmalloc(sizeof(struct simple_gpio_fan_local), GFP_KERNEL);
	if (!lp) {
		dev_err(dev, "Cound not allocate simple-gpio-fan device\n");
		return -ENOMEM;
	}
	dev_set_drvdata(dev, lp);

	lp->num_gpios = gpiod_count(dev, NULL);
	if (lp->num_gpios < 0) {
		dev_err(dev, "Error getting fan gpio\n");
		rc = lp->num_gpios;
		goto error1;
	}

	lp->gpios = devm_kzalloc(dev, lp->num_gpios * sizeof(struct gpio_desc *), GFP_KERNEL);

	if (!lp->gpios) {
		dev_err(dev, "Error allocating memory for fan gpio\n");
		rc = -ENOMEM;
		goto error1;
	}

	for (int i = 0; i < lp->num_gpios; i++) {
		lp->gpios[i] = devm_gpiod_get_index(dev, NULL, i, GPIOD_OUT_LOW);
		if (IS_ERR(lp->gpios[i])) {
			rc = PTR_ERR(lp->gpios[i]);
			dev_err(dev, "Error getting fan gpio %d\n", i);
			goto error1;
		}
	}

	/* set direction of gpio 0 to out */
	rc = gpiod_direction_output(lp->gpios[0], 1);

	if (rc) {
		dev_err(dev, "Error setting direction of fan gpio 0\n");
		goto error1;
	}

	// /* set output to low for gpio 0 */
	// gpiod_set_value(lp->gpios[0], 0);

	lp->cdev = devm_thermal_of_cooling_device_register(dev, np,
				(char*)pdev->name, lp, &gpio_fan_cool_ops);

	/* Verify the registration */

	if (IS_ERR(lp->cdev)) {
		dev_err(dev, "Error registering cooling device\n");
		rc = PTR_ERR(lp->cdev);
		goto error1;
	}

	// lp->mem_start = r_mem->start;
	// lp->mem_end = r_mem->end;

	// if (!request_mem_region(lp->mem_start,
	// 			lp->mem_end - lp->mem_start + 1,
	// 			DRIVER_NAME)) {
	// 	dev_err(dev, "Couldn't lock memory region at %p\n",
	// 		(void *)lp->mem_start);
	// 	rc = -EBUSY;
	// 	goto error1;
	// }

	// lp->base_addr = ioremap(lp->mem_start, lp->mem_end - lp->mem_start + 1);
	// if (!lp->base_addr) {
	// 	dev_err(dev, "simple-gpio-fan: Could not allocate iomem\n");
	// 	rc = -EIO;
	// 	goto error2;
	// }

	// /* Get IRQ for the device */
	// r_irq = platform_get_resource(pdev, IORESOURCE_IRQ, 0);
	// if (!r_irq) {
	// 	dev_info(dev, "no IRQ found\n");
	// 	dev_info(dev, "simple-gpio-fan at 0x%08x mapped to 0x%08x\n",
	// 		(unsigned int __force)lp->mem_start,
	// 		(unsigned int __force)lp->base_addr);
	// 	return 0;
	// }
	// lp->irq = r_irq->start;
	// rc = request_irq(lp->irq, &simple_gpio_fan_irq, 0, DRIVER_NAME, lp);
	// if (rc) {
	// 	dev_err(dev, "testmodule: Could not allocate interrupt %d.\n",
	// 		lp->irq);
	// 	goto error3;
	// }

	// dev_info(dev,"simple-gpio-fan at 0x%08x mapped to 0x%08x, irq=%d\n",
	// 	(unsigned int __force)lp->mem_start,
	// 	(unsigned int __force)lp->base_addr,
	// 	lp->irq);
	return 0;
error1:
	kfree(lp);
	dev_set_drvdata(dev, NULL);
	return rc;
}

static int simple_gpio_fan_remove(struct platform_device *pdev)
{
	struct device *dev = &pdev->dev;
	struct simple_gpio_fan_local *lp = dev_get_drvdata(dev);
	kfree(lp);
	dev_set_drvdata(dev, NULL);
	return 0;
}

#ifdef CONFIG_OF
static struct of_device_id simple_gpio_fan_of_match[] = {
	{ .compatible = "xlnx,simple-gpio-fan", },
	{ /* end of list */ },
};
MODULE_DEVICE_TABLE(of, simple_gpio_fan_of_match);
#else
# define simple_gpio_fan_of_match
#endif


static struct platform_driver simple_gpio_fan_driver = {
	.driver = {
		.name = DRIVER_NAME,
		.owner = THIS_MODULE,
		.of_match_table	= simple_gpio_fan_of_match,
	},
	.probe		= simple_gpio_fan_probe,
	.remove		= simple_gpio_fan_remove,
};

static int __init simple_gpio_fan_init(void)
{
	printk("<1>simple_gpio_fan driver loaded\n");

	return platform_driver_register(&simple_gpio_fan_driver);
}


static void __exit simple_gpio_fan_exit(void)
{
	platform_driver_unregister(&simple_gpio_fan_driver);
	printk(KERN_ALERT "simple_gpio_fan unloaded\n");
}

module_init(simple_gpio_fan_init);
module_exit(simple_gpio_fan_exit);
